### ISSUE TITLE
Having Trouble adding this plugin to Ultimaker Cura

### ISSUE THREAD

**Issue by R2MGaming** [vgdh/seam-slope-postprocessor#3]
Hi. I came across this little plugin which is perfect for scarf seams, and noticed it didn't say anything about Ultimaker Cura (since I had more trouble with OrcaSlicer, PrusaSlicer and Repetier Host with printing some test prints) so I had to find out how to install this in the latest version of Cura to see if it'll work or not, but I am currently having trouble trying to get this to work with Cura 5.7.1. Do you know how to properly install it for Cura, or does it need a version meant for that?

**Comment by vgdh** [comment]
It doesn't work correctly with cura gcode. It can be done, but because orca has already implemented this feature I have no intention of further develop or support this script. You can feel free to fork it and do some minor changes to make it work 😉.
