### ISSUE TITLE
Decode Error

### ISSUE THREAD

**Issue by jpaxer** [vgdh/seam-slope-postprocessor#4]
When I run the script in prusaslicer I get the error

`File "", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 1361: invalid continuation byte`

**Comment by vgdh** [comment]
It can be done, but because orca has already implemented this feature I have no intention of further develop or support this script. You can feel free to fork it and do some minor changes to make it work 😉.
